import type { Metadata } from "next";
import { IBM_Plex_Sans, Cormorant_Garamond } from "next/font/google";
import { ViewTransitions } from "next-view-transitions";
import "./globals.css";
import Header from "@/sections/Header";

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibmPlex-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const cormorantSans = Cormorant_Garamond({
  variable: "--font-cormorant-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${ibmPlexSans.variable} ${cormorantSans.variable} antialiased font-ibmPlex-sans`}
        >
          <Header />
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
